/** Vocabulary word stored in Supabase `words` table.
 *  The `embedding` column is excluded from client fetches — use match_words() RPC instead. */
export interface Word {
  id: string;
  word: string;
  correct_definition: string;
  /** Exactly 3 wrong answer choices. */
  distractors: string[];
  /** Difficulty rating 1–10. */
  difficulty: number;
}

/** User profile stored in `public.users`.
 *  Single source of truth for display data — never replicated to other tables. */
export interface UserProfile {
  id: string;
  name: string | null;
  avatar_url: string | null;
  /** 'player' (default) or 'admin'. Granted via SQL: update users set role='admin'. */
  role: 'player' | 'admin';
  created_at: string;
  updated_at: string;
}

/** Row returned by the `leaderboard_ranked` view.
 *  user_name / user_photo come from the join with `public.users` — not stored redundantly. */
export interface LeaderboardEntry {
  id: string;
  user_id: string;
  /** Joined from public.users.name */
  user_name: string | null;
  /** Joined from public.users.avatar_url */
  user_photo: string | null;
  score: number;
  /** Leaderboard category, e.g. 'global', 'weekly', 'hard-mode'. */
  type: string;
  created_at: string;
}

/** Analytics record for a completed game round, stored in `game_sessions`. */
export interface GameSession {
  id: string;
  user_id: string;
  score: number;
  word_count: number;
  max_score: number;
  type: string;
  created_at: string;
}

/** Per-word result within a game session, stored in `session_words`. */
export interface SessionWord {
  session_id: string;
  word_id: string;
  /**
   * Canonical slot the player chose, independent of shuffle order.
   * 0 = correct_definition, 1–3 = distractors[0..2], null = timed out.
   */
  answer_index: number | null;
  /** Seconds elapsed when the player answered (timer_seconds - time_left). */
  time_taken: number | null;
  /** Generated by the DB from answer_index — always consistent, not stored by the client. */
  correct: boolean;
}

/** Per-user performance for a single word, stored in `user_word_stats`. */
export interface UserWordStat {
  user_id: string;
  word_id: string;
  correct_count: number;
  incorrect_count: number;
  last_seen_at: string;
  last_correct: boolean | null;
}

/**
 * Game configuration stored in Supabase `game_config` table (single row, id=1).
 * Written exclusively by admins; read by all authenticated players.
 */
export interface GameConfig {
  /** Number of words per round. */
  word_count: number;
  /** Seconds per word countdown. */
  timer_seconds: number;
  /** Only include words with difficulty >= this value. */
  difficulty_min: number;
  /** Only include words with difficulty <= this value. */
  difficulty_max: number;
}

export const DEFAULT_GAME_CONFIG: GameConfig = {
  word_count: 10,
  timer_seconds: 10,
  difficulty_min: 1,
  difficulty_max: 10,
};
